/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    F7App: typeof import('framework7-vue')['f7App']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7Panel: typeof import('framework7-vue')['f7Panel']
    F7Popup: typeof import('framework7-vue')['f7Popup']
    F7View: typeof import('framework7-vue')['f7View']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'i18n-t': typeof import('vue-i18n')['i18n-t']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Logo: typeof import('./assets/logo.svg?component')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
